# This is a basic workflow to help you get started with Actions

name: Simple Workflow

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: | 
          echo "Hello GH Simple Action"
          echo "This is second line"
      - name: Print Goodbye
        run: echo "Done with first job"
